id: 74c3bda5-cdae-4af3-ab54-daddfbe8bc70
name: Archive Repository Settings Updated
description: Detects when archive repository settings updated in Veeam infrastructure,
  which could indicate configuration changes that need monitoring.
severity: Low
status: Available
requiredDataConnectors:
  - connectorId: Syslog
    dataTypes: 
      - Syslog
  - connectorId: SyslogAma
    dataTypes: 
      - Syslog
queryFrequency: 3h
queryPeriod: 3h
triggerOperator: gt
triggerThreshold: 0
tactics:
- DefenseEvasion
relevantTechniques:
- T1562.001
query: "Veeam_GetSecurityEvents\n| where instanceId == 29800\n| extend Name =  extract(\"\
  Name=\\\"([^\\\"]*)\\\"\", 1, SyslogMessage)\n| project\n    Date = format_datetime(TimeGenerated,\
  \ 'dd.MM.yyyy HH:mm'),\n    DataSource = original_host,\n    EventId = instanceId,\n\
  \    UserName = user,\n    [\"Object Name\"] = Name,\n   MessageDetails = Description,\n\
  \   Severity = SeverityDescription"
version: 1.0.0
kind: Scheduled
customDetails:
  Date: Date
  VbrHostName: DataSource
  EventId: EventId
  MessageDetails: MessageDetails
  Severity: Severity
