# THIS WORKFLOW WILL RUN WHEN WE ADD SLASH COMMAND LIKE '/arm-ttk', '/ARM-TTK', '/Arm-Ttk', 'armttk' or 'ARMTTK'
name: Slash Command ARM-TTK Tests

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  run-arm-ttk:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork && github.event.issue.pull_request && contains(fromJson('["/armttk", "/Armttk", "/ARM-TTK", "/ARMTTK", "/arm-ttk", "/ArmTtk"]'), github.event.comment.body) }}
    outputs:
      solutionName: ${{ steps.step1.outputs.solutionName }}
      mainTemplateChanged: ${{ steps.step1.outputs.mainTemplateChanged }}
      createUiChanged: ${{ steps.step1.outputs.createUiChanged }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 5
          ref: refs/pull/${{ github.event.issue.number }}/head
      - shell: pwsh
        id: step1
        name: Identify Changes in PR
        run: |
          try {
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module powershell-yaml -Force
            ./.script/package-automation/arm-ttk-tests.ps1
          }
          catch {
            Write-Error "Failed to run ARM-TTK tests: $_"
            exit 1
          }

      - uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        id: publishGithubPackage
        name: Run ARM-TTK
        if: ${{ success() && steps.step1.outputs.solutionName != '' && (steps.step1.outputs.mainTemplateChanged == 'true' || steps.step1.outputs.createUiChanged == 'true') }}
        with:
          context: .
          file: ./.github/actions/Dockerfile
          push: false
          provenance: false
          build-args: |
            SolutionName=${{ steps.step1.outputs.solutionName }}
            mainTemplateChanged=${{ steps.step1.outputs.mainTemplateChanged }}
            createUiChanged=${{ steps.step1.outputs.createUiChanged }}
